name: cytospace
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - numpy=1.22.2
  - lap=0.4.0
  - scipy=1.8.0
  - pip=22.0.4
  - pandas=1.4.1
  - matplotlib=3.5.1
  - r-seurat=3.1.4
  - pip:
    - lapjv==1.3.14
    - ortools==9.2.9972
